### ISSUE TITLE
Can't login to Portal

### ISSUE THREAD

**Issue by Lonerist** [chrsep/Kingfish#18] opened 2017-08-26 16:33 UTC
I can't login to my Portal (with the latest update). It says "Failed to authenticate with Bimay", even though I got my username & password right.

**Comment by felixlix45** [comment] 2017-08-27 04:04
Are you B21?

**Comment by Lonerist** [comment] 2017-08-27 08:28
I'm B20, and had no trouble logging in before......
I tried with my sister's who is B19 and still failed to login

**Comment by chrsep** [comment] 2017-08-27 12:12
Hi @Lonerist , there were some changes to Binusmaya a while back that causes lots of failed sign in.

Today, the failed sign in seems to happen to half of Portal's users. I have an idea about what's wrong with B21, but B20 and lower should have been able to sign in normally. 

Me and my friends are not affected though, so it's quite hard to pinpoint the cause. It'll take some time to fix. More info in #16. 

Meanwhile, you can try to see what's wrong yourself if you want. Just clone the fixCaptcha branch and run the code through Android Studio. You can then try to sign in and monitor all Portal's network activity from Chrome's devtool by opening `chrome://inspect/#devices` on chrome.

**Comment by chrsep** [comment] 2017-09-18 09:40
@Lonerist Do you still have any trouble logging in to Portal? Can you now see the schedule, grades and finances?

**Comment by Lonerist** [comment] 2017-09-18 10:43
It's been a long time since my last login, so I decided to try it today.......
Somehow it worked now, despite not getting an update. So I guess it was just a matter of time........

**Comment by chrsep** [comment] 2017-09-18 15:14
Well that's good news, does the schedules, grades and finance works too?

**Comment by Lonerist** [comment] 2017-09-19 04:32
It works fine now. I don't see any more problem in my phone......

**Comment by chrsep** [comment] 2017-09-19 12:30
Great, I'll close this issue for now

**Closed by chrsep** 2017-09-19 12:30 UTC
