### ISSUE TITLE
Binusmaya is giving us weird data

### ISSUE THREAD

**Issue by Mondoe** [chrsep/Kingfish#27] opened 2017-10-31 00:48 UTC
It says Binusmaya is giving us weird data, and im unable to update my class sched. Although i can still login. Pls help?

**Comment by chrsep** [comment] 2017-11-28 10:19
Hi @Mondoe , I'm really sorry for my very late reply. There are some random request failure caused by something about undefined EmployeeId from Binusmaya, I just can't get my head around it yet. Do you still experiencing this issue?

**Comment by chrsep** [comment] 2018-05-11 12:31
I'll close this issue for now, feel free to reopen if there is still issue.

**Closed by chrsep** 2018-05-11 12:31 UTC
